### PR TITLE
Misc typo corrections in comments. Zero functionality added.

### PR DESCRIPTION
**Pull request by colonwq**

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
tjalms!

**Comment by jposada202020** [comment]
@colonwq Hello and Thanks, there are some changes need to be done on the `font_maker.py` file not related with your PR changes  in order to the CI to pass the test, let me know if you would like to do them. or I could also do a separate PR for these. Thanks again

**Comment by jposada202020** [comment]
I triggered the CI again to verify changes after PR on the `font_maker.py` was merged.  The CI pass and changes were already approved. Merging.

**Comment by jposada202020** [comment]
@colonwq Thanks for your contribution

**Pull request merged**
