### PR TITLE
[NOT FULLY TESTED] Renamed simpletest file and added second simpletest file

### PR DESCRIPTION
**Pull request by dherrada**
@AdinAck wrote and tested gfx_ssd1322. I still need someone to test gfx_ili3941_simpletest.py on their ili3941 because I don't own one.

### CODE REVIEW

**Comment by dherrada** [comment]
Lol, not sure how this happened, but I think I must have done git add . from the docs file and pushed that without doing git status. Should be fixed now

**Comment by dherrada** [comment]
Also, the example file was taken directly from micropython, so I'd like to verify that it works before putting it in the docs as an example

**Comment by makermelissa** [comment]
Ok, good point on the testing.

**Comment by dherrada** [comment]
The reason I had the ili9341 in the filename is that there's two simpletests, each for different screens. I think that it may be a good idea to combine the files into one simpletest that works for both although I don't have the hardware for that yet. I'll put this on my to-do list and hopefully get to it sometime early next week.

**Comment by makermelissa** [comment]
I understand. The reason I requested the ILI9341 is because it's the more popular of the displays. In the arduino gfx library, we also use the ILI9341 for the travis tests.

**Comment by makermelissa** [comment]
I think you're right about the testing and I'm pretty sure this won't work without changes. Calls like machine.Pin() are MicroPython specific and shouldn't even work on the linux side. This is most likely why gfx_simpletest.py was empty. Nobody had rewritten the ili9341 test to be CP/Blinka compatible. So I'll go with not renaming it simpletest for now, but please put back the blank file and maybe add some kind of docstring that says nobody has written one and to request somebody to do it. However, this library may be phased out before that happens.

**Comment by ladyada** [comment]
please deprecate this library, we should use only displayio and pillow :) we may want to adapt some of this code to the displayio shapes library

**Comment by dherrada** [comment]
Ok

**Comment by ladyada** [comment]
hiya after some thought, i was totally wrong, we should keep this for a bit longer. reopening :)

**Comment by dherrada** [comment]
Ok. Sounds good

**Comment by dherrada** [comment]
Closing because both of these screens have their own driver repos with their own simpletests

**Pull request closed without merging**
